update readme and changelog; revert release.yml changes
Co-authored-by: Matt Wylder <mwylder@paypal.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -19,7 +19,7 @@ jobs:
         run: sudo xcode-select -switch /Applications/Xcode_14.0.app
 
       - name: Check for unreleased section in changelog
-        run: grep "## unreleased (next-major-version)" CHANGELOG.md || (echo "::error::No unreleased section found in CHANGELOG"; exit 1)
+        run: grep "## unreleased" CHANGELOG.md || (echo "::error::No unreleased section found in CHANGELOG"; exit 1)
 
       - name: Set git username and email
         run: |
@@ -35,7 +35,7 @@ jobs:
       - name: Update version
         run: |
           today=$(date +'%Y-%m-%d')
-          sed -i '' 's/## unreleased (next-major-version)/## '"${{ github.event.inputs.version }}"' ('"$today"')/' CHANGELOG.md
+          sed -i '' 's/## unreleased.*/## '"${{ github.event.inputs.version }}"' ('"$today"')/' CHANGELOG.md
           sed -i '' 's/\(s\.version *= *\).*/\1"'"${{ github.event.inputs.version }}"'\"/' Braintree.podspec
           sed -i '' 's/braintreeSDKVersion: String =.*/braintreeSDKVersion: String = "${{ github.event.inputs.version }}"/' Sources/BraintreeCore/BTCoreConstants.swift
           plutil -replace CFBundleVersion -string ${{ github.event.inputs.version }} -- 'Demo/Application/Supporting Files/Braintree-Demo-Info.plist'
